# Generated by Django 4.2 on 2024-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_to_terms',
            field=models.BooleanField(default=False, verbose_name='Agree to Terms and Privacy'),
        ),
    ]
