# Generated by Django 4.2 on 2024-06-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=230)),
                ('email', models.EmailField(max_length=254)),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Get In Touch',
            },
        ),
    ]
